### ISSUE TITLE
Método para obtener el folio siguiente disponible

### ISSUE THREAD

**Issue by leonardobarrientosc** [LibreDTE/libredte-lib#15]

**Comment by estebandelaf** [comment]
Leonardo,

No es parte de la biblioteca hacer la gestión de folios, ni lo será en el futuro. La biblioteca no tiene un "almacenamiento", no sabe si tiene folios "guardados", eso es parte de la aplicación que construyas.

Si necesitas ver un ejemplo de como obtener el último folio disponible revisa el módulo Dte, específicamente el método \website\Dte\Model_Contribuyente::getFolio()[1]

Saludos!

[1] https://github.com/LibreDTE/libredte-sowerphp/blob/master/Model/Contribuyente.php#L561

**Comment by leonardobarrientosc** [comment]
Si pasas el XML de folios a la LIB hay unos file_get_content que hacen eso en los ejemplos, entonces, al final igual está almacenando información de los folios, la pregunta clave es cada usuario pone el folio disponible siguiente o es deseable sea automático. Yo creo lo segundo.

**Comment by estebandelaf** [comment]
Leonardo,

Los file_get_contents no son parte de la biblioteca, me refiero a los fuentes que encuentras en "lib/Sii" Los ejemplos claro, ya que "simulan", bien a la mala, lo que haría una aplicación que use la biblioteca. El objetivo de los ejemplos no es mostrar como hacer una aplicación, es mostrar como se podría usar la biblioteca.

Como tu dices, efectivamente la asignación de folios debe ser automática y jamás debe estar a cargo del usuario elegir el folio, pero, como dije antes, esa es la pega de tu aplicación. En el caso de LibreDTE dicha pega se hace en el módulo Dte que te comenté.

Recuerda, la biblioteca es sólo eso, una biblioteca, no un sistema de facturación. Si necesitas un sistema de facturación te recomiendo ver los otros proyectos.

Saludos!

**Comment by leonardobarrientosc** [comment]
Ya.
