### ISSUE TITLE
Acerca del uso

### ISSUE THREAD

**Issue by leonardobarrientosc** [LibreDTE/libredte-lib#16]
Hola Esteban, una consulta: Estoy usando lib libreDTE para generar boletas electrónicas de prueba de un cliente, ya que uso lib libreDTE sin hacer ninguna modificación, solo instancio las clases ¿Debo liberar el software que hace las llamadas igualmente? (Estoy usando el LIB, no la suite Web)  

Según leo de la licencia: 

"Este software se encuentra bajo los términos de la licencia GPL 3 que puedes encontrar en el archivo COPYING.", pero lo que me deja con la duda es: 

"* Si utilizas LibreDTE en tu software, dicho software deberá ser publicado bajo licencia GPL o bien alguna otra licencia compatible con la GPL."

**Comment by estebandelaf** [comment]
Leonardo,

Efectivamente, al usar LibreDTE debes liberar tu software bajo una licencia compatible, la GPL es una de ellas. Debes hacerlo igualmente ya que estás integrando la biblioteca dentro de tu sistema. Y no es sólo liberar la parte que "hace las llamadas", debes liberar el software completo. De no hacerlo estarías violando los términos y condiciones de LibreDTE, lo cual obviamente es ilegal.

Además mencionar que la licencia actual es la AGPL y los términos y condiciones de uso del proyecto los encuentras en https://wiki.libredte.cl/doku.php/terminos

Saludos,

**Comment by leonardobarrientosc** [comment]
Comprendo, No usaré LibreDTE, no te preocupes.

Gracias por contestar.
