### ISSUE TITLE
Problemas validación de firma XML intercambio SII

### ISSUE THREAD

**Issue by estebandelaf** [LibreDTE/libredte-lib#18]
Desde mayo se han detectado problemas al validar la firma del XML de intercambio del SII. Suponiendo que el XML del SII está ok, se asume existe un bug. Por el momento se omite la validación de las firmas https://github.com/LibreDTE/libredte-lib/commit/6f34d9316aa853934ef2cda4beeae4c21ad32a51 sin embargo esto es incorrecto y se deben verificar los métodos que hacen la validación para corregir.

Adicionalmente, se necesitan revisiones de otros usuarios que puedan verificar si LibreDTE valida las firmas de documentos XML que reciban.

Es extraño porque si el SII acepta los DTE entonces las firmas deberían estar OK, sin embargo LibreDTE no acepta todas las firmas a pesar que los DTE han sido aceptados por el SII. Teorías:
1. LibreDTE no está validando correctamente (podría ser incluso algún problema de codificación).
2. Los que envían los XML que son rechazados por firma envían documentos diferentes a los que mandan al SII, y por eso la firma es inválida pero son aceptados por el SII.

De todas formas lo único que se podría hacer es verificar 1.

Reporte inicial en: https://groups.google.com/d/topic/libredte/SWyfGcTXs48/discussion

**Comment by estebandelaf** [comment]
Una posible solución: https://groups.google.com/d/msg/libredte/5pPpv725Jgc/4gbDUZm8CgAJ

Esperando a confirmar si efectivamente soluciona el problema.

**Comment by dansanti** [comment]
Estimado, creo el problema se da en que eliminas el atributo que se hereda,

xmlns="http://www.sii.cl/SiiDte"

https://github.com/LibreDTE/libredte-lib/blob/2c3f0fabb81eeaa2ea8b58936524fe13b59bc777/lib/Sii/Dte.php#L1593
Me pasó en python que quitando solamente 

xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

Da el mismo digest
