### ISSUE TITLE
Cesion de documentos

### ISSUE THREAD

**Issue by Adoniasv** [LibreDTE/libredte-lib#19]
Hola

Modifique tu código y agregue la opción para Cesión de documentos.

Como se puede hacer para crear una rama?

**Comment by estebandelaf** [comment]
Hola, los pasos están aquí: https://github.com/LibreDTE/libredte-lib#contribuir-al-proyecto Saludos!

**Comment by mgutierrezvBPC** [comment]
Estimados,
 También estoy trabajando sobre la cesión y recesión  de facturas electrónicas . he estado pegado en la firma del AEC y me gustaría conocer tu código Adoniasv , como puede ser posible? , lograste crear la rama?. He revisado algunos foros , pero ninguno trabajando en PHP,( lenguaje que estoy creando mi app). Me alegro que exista esta incitativa. Estoy revisando el código para poder integrarlo a mi desarrollo. y también a posterior ser un aporte a esta comunidad.

**Comment by Adoniasv** [comment]
Esteban

Subi los documentos que generan automaticamente la cesión.

Favor verificar

**Comment by Adoniasv** [comment]
Esteban

Cuando envio el commit de los documentos que modifique para la cesion electronica, me da error?

Porque pasa eso?

**Comment by estebandelaf** [comment]
Hola, puedes por favor crear una sola rama con todos los cambios y hacer un sólo pull request. De esta forma clono tu rama y la verifico antes. Saludos!

**Comment by Adoniasv** [comment]
Shurra.. ahi me pillaste como se hace eso?? :s

**Comment by mlopez-espol** [comment]
http://gitevangelism.blogspot.cl/2011/08/fusionar-commits.html

**Comment by llongeri** [comment]
> recesión

Hola consulta, tienes un ejemplo de recesión? estoy tratando de generar una pero SII me responde "Doc. ya esta cedido, para cederlo nuevamente debe incluir cesion anterior", debo tener algún problema con como incluir la historia de cesiones.

**Comment by Adoniasv** [comment]
> > recesión
> 
> Hola consulta, tienes un ejemplo de recesión? estoy tratando de generar una pero SII me responde "Doc. ya esta cedido, para cederlo nuevamente debe incluir cesion anterior", debo tener algún problema con como incluir la historia de cesiones.

Cuando Cedes una factura ya no es tuya, la debe ceder la persona jurídica que la recibió

**Comment by llongeri** [comment]
> > > recesión
> > 
> > 
> > Hola consulta, tienes un ejemplo de recesión? estoy tratando de generar una pero SII me responde "Doc. ya esta cedido, para cederlo nuevamente debe incluir cesion anterior", debo tener algún problema con como incluir la historia de cesiones.
> 
> Cuando Cedes una factura ya no es tuya, la debe ceder la persona jurídica que la recibió

Gracias por responder.

Justamente estoy tratando de recederla como la persona jurídica que la recibió, pero creo que tengo algún problema con la data misma que se carga en el AEC.

En particular, revisando el código de LibreDTE (libredte-lib/lib/Sii/Factoring/Cesion.php:127), se ve que en la nueva cesión (DocumentoCesion con SeqCesion=2) el Cedente lo pueblan con los datos del emisor de la factura y no con la persona jurídica que recibió la primera cesión. No sé si será un detalle a solucionar o así se debe poblar.
Ahora, puede que algo más se me escape, por eso me interesaba ver un ejemplo correcto de AEC con 2 cesiones pero no he encontrado.
