### ISSUE TITLE
LBR - 3 - Error en Detalle -- Libro Compra/Venta

### ISSUE THREAD

**Issue by Adoniasv** [LibreDTE/libredte-lib#20]
Estimado

Cuando agregas un libro de compra o venta en formato CSV, y tienes una nota de crédito que modifica detalles del receptor (MntNeto MntExe MntIVA == 0), PHP borra ese valor en cero, provocando un error en el SII

```
// agregar detalle desde un archivo CSV con ; como separador
$LibroCompraVenta->agregarVentasCSV($fcsv);

// enviar libro de compras y mostrar resultado del envío: track id o bien =false si hubo error
$LibroCompraVenta->setCaratula($caratula);
$LibroCompraVenta->setFirma($Firma);
$xml = $LibroCompraVenta->generar(); // generar XML
```

Creo que el error se encuentra en el archivo PHP que genera la normalización:

```
private function normalizarDetalle(array &$detalle)
    {
        // agregar nodos (esto para mantener orden del XML)
        $detalle = array_merge([
            'TpoDoc' => false,
            'NroDoc' => false,
            'Anulado' => false,
            'TpoImp' => 1,
            'TasaImp' => false,
            'FchDoc' => false,
            'CdgSIISucur' => false,
            'RUTDoc' => false,
            'RznSoc' => false,
            'MntExe' => false,
            'MntNeto' => false,
            'MntIVA' => false,
            'MntActivoFijo' => false,
            'MntIVAActivoFijo' => false,
            'IVANoRec' => false,
            'IVAUsoComun' => false,
            'OtrosImp' => false,
            'IVARetTotal' => false,
            'IVARetParcial' => false,
            'MntSinCred' => false,
            'MntTotal' => false,
            'IVANoRetenido' => false,
        ], $detalle);
```

Adjunto respuesta del SII

> # Resultado de Validacion de Envio de Libro Tributario
> 
> Identificador de Envio      : 1645002436
> Fecha de Recepcion          : 07/08/2016 20:09:40
> Estado del Envio de Libro   : LRH - Envio de Libro Rechazado - Descuadrado
> Tipo de Segmento            : TOTAL
> Numero de Segmento          :   0
> # Detalle de Errores del Envio de Libro Tributario
> 
> LBR - 3 - Error en Detalle - Falta [MntNeto MntExe MntIVA]    T:[61]-F:[642]
> LBR - 3 - Errores en RUT, Fecha y Tipo De documento - solo se muestran los primeros -

**Comment by estebandelaf** [comment]
Si entendí el problema, te refieres por ejemplo a una modificación de giro
de receptor donde el total es 0. Si ese es el caso, revisa que lo estés
haciendo bien, porque esos casos con montos en 0 están correctos y el
proceso de normalización también. De hecho ese caso (corrección de giro con
monto 0) es parte del set de prueba que debe ser aprobado en certificación.
Saludos!

**Comment by Adoniasv** [comment]
Mira, el set de prueba se basa en un XML, pero cuando es un csv puto es distinto.

Te adjunto el CSV que me dio el error. No se si sera la versión del PHP o un tema de codificación del CSV

Linea 479

[LIBVENTA_2016-06.csv.zip](https://github.com/LibreDTE/libredte-lib/files/409051/LIBVENTA_2016-06.csv.zip)

**Comment by DeathEmpire** [comment]
un poco viejo, pero en la funcion agregarVentasCSV valida los datos con !empty(monto) por lo que el 0 no lo toma encuenta, puedes ponerle valor por defecto 0 o validar contra ""
