### ISSUE TITLE
Inconsistencia en el idioma

### ISSUE THREAD

**Issue by javitoxhz** [LibreDTE/libredte-lib#3]
Hay clases en inglés y otras en español, ¿a qué se debe esto?

**Comment by estebandelaf** [comment]
Ninguna razón en particular. Algunas están basadas en otras clases que originalmente estaban en inglés. Algunas veces es más fácil escribir en inglés un método o una clase y otras veces no se puede en inglés (cómo la clase Arreglo, no se podía usar Array). Saludos!
