### ISSUE TITLE
(CRT-3-18) RUT Receptor (Caratula) Invalido - [XXXX6500-1]

### ISSUE THREAD

**Issue by Adoniasv** [LibreDTE/libredte-lib#30]
Hola

A alguno de ustedes le a pasado que al enviar a producción el DTE le da error???

Cuando coloco el RUT del SII no da problemas (60803000-K) pero cuando coloco el rut del receptor da error de Carátula.

El problema de esto, es que al momento de enviar el EnvioDTE a Acepta, Custodium o algunos sistemas SAP, no recepcionan el DTE ya que la carátula es para el SII.

**Comment by wilfredinni** [comment]
Hola, pudiste encontrar una solución? gracias

**Comment by estebandelaf** [comment]
https://github.com/LibreDTE/libredte-lib/issues/78

PD: no es una issue del código.
