### ISSUE TITLE
IVA Ret parcial

### ISSUE THREAD

**Issue by dansanti** [LibreDTE/libredte-lib#31]
Hola!

En el caso de que sea retención parcial se debe de todos modos descontar to el IVA del MOnto o se debe descontar lo que efectivamente fue retenido?

https://github.com/LibreDTE/libredte-lib/blob/master/lib/Sii/LibroCompraVenta.php#L191

**Comment by estebandelaf** [comment]
Si es retención parcial, se debe descontar sólo la parte que se retiene. Sin embargo el enlace que envías es para el IVA no recuperable. En cuyo caso el IVA no se descuenta, sino que sólo se informa la parte que no es recuperable. Saludos!
