### ISSUE TITLE
Obtener información de un solo contribuyente

### ISSUE THREAD

**Issue by rhyudek1** [LibreDTE/libredte-lib#33]
Estimado,

Un gusto en saludar, quería saber si existe la posibilidad de utilizar el método
```php
\sasco\LibreDTE\Sii::getContribuyentes($firmaElectrónica)
```
para traer la información de sólo una empresa?
ya sea por su rut u otro campo.

Gracias por tu tiempo y por compartir la librería.

**Comment by estebandelaf** [comment]
Hola,

En principio no, ya que ese método si o si descarga un archivo con todos los datos de todos los contribuyentes Tu después podrías filtrar por el que te interesa pero hacer eso cada vez es ineficiente. Lo mejor es descargar el archivo una vez al día y guardarlo localmente para poder hacer las búsquedas.

Saludos!
