### ISSUE TITLE
Obtener información de contribuyentes dejó de funcionar

### ISSUE THREAD

**Issue by rhyudek1** [LibreDTE/libredte-lib#34]
Estimado,

Hace algunas semanas estaba utilizando una función para rescatar los datos de los contribuyentes desde el SII ( servidor maullin ) y funcionaba perfectamente, pero estos días he estado intentando utilizarla y ya no me trae ningún dato de respuesta. 

habrá cambiado algo?

```php
<?php
$firma = new \sasco\LibreDTE\FirmaElectronica([
    'data' => \Storage::get('certificado.p12'), // contenido del archivo certificado.p12
    'pass' => '*******', // oculta
]);
\sasco\LibreDTE\Sii::setAmbiente(\sasco\LibreDTE\Sii::CERTIFICACION);
\sasco\LibreDTE\Sii::setServidor($servidor); // maullin
$datos = \sasco\LibreDTE\Sii::getContribuyentes($firma);
print_r($datos); // imprimo los datos de retorno, no viene información de retorno
```

no he modificado en nada este código y antes funcionaba.
Quedo atento a comentarios,
gracias de antemano.

**Comment by estebandelaf** [comment]
Buenas tardes,

Por favor indica el repositorio donde tienes publicado ese código para revisar.

Saludos!

**Comment by estebandelaf** [comment]
Esto funciona, hay temas en el grupo de Google donde se ha hablado de esto. Saludos!
