### ISSUE TITLE
Acentos en Folios

### ISSUE THREAD

**Issue by Adoniasv** [LibreDTE/libredte-lib#36]
Estimados.

Cuando importo un timbre en el cual el nombre del cliente posee acento, la librería arroja el siguiente error:

`Archivo de folios no pudo ser verificado`

**¿Alguien más tiene este problema?**

**Comment by mi-lopez** [comment]
Si, encontré como solucionarlo pero es media weona la forma, pero por ahora me funciona, debes bajar el CAF y con el SublimeText irte a Save with Encoding y seleccionar UTF-8. No sé si es falla del SII que esos XML no tengan la codificación UTF-8 o que, pero de esa forma lo solucionas.

**Comment by estebandelaf** [comment]
@Adoniasv esto era un bug y ya está corregido, se subió una actualización de la biblioteca que lo corrige. Básicamente se convierte el archivo de folios a UTF-8 antes de tratar de cargarlo.

@mi-lopez no es falla del SII, ellos usan para todo la codificación ISO8859-1 en cambio LibreDTE usa para todo UTF-8, excepto para los XML de salida, que ahí se usa la que espera el SII. Así que está bien que los XML del SII estén en esa codificación.
