### ISSUE TITLE
obtener facturas de proveedores

### ISSUE THREAD

**Issue by gbelmm** [LibreDTE/libredte-lib#38]
se puede obtener las facturas que se generaron al cliente o sea que les envian o solo se pueden obtener del mail ?

saludos y gracias

**Comment by estebandelaf** [comment]
El XML se puede obtener sólo de un correo.

Si tienes nuevas consultas, que no son de código, por favor hacerlas en el foro en https://groups.google.com/forum/#!forum/libredte

**Comment by estebandelaf** [comment]
El servicio web https://doc.libredte.cl/api/#!/DteRecibidos/get_dte_dte_recibidos_info_emisor_dte_folio_receptor ahora permite pasar el parámetro getXML=1 que entregará el XML del DTE recibido (para eso el DTE tiene que provenir de un intercambio, y haber sido aceptado en la bandeja).

**Comment by gbelmm** [comment]
genial probando..
