### ISSUE TITLE
Problema instalación libredte lib

### ISSUE THREAD

**Issue by ricardopxl** [LibreDTE/libredte-lib#4]
Esteban,

He probado tu framework y de verdad te felicito: http://hostingrc.com/sii/sowerphp-master/

He intentado configurar la webapp pero me ha sido imposible, he intentado todo lo que se me ocurre siguiendo la documentación disponible: http://hostingrc.com/sii/app/ queda en blanco.

Te cuento, descargué sower de github, lo hice arrancar (http://hostingrc.com/sii/sowerphp-master/), luego descargue la webapp Libredte, reemplace los datos y cargue la carpeta Vendor, cambio el config-dist por config. Y luego arroja: http://hostingrc.com/sii/app/.

Espero me puedas orientas.

Saludos,

**Comment by estebandelaf** [comment]
Hola Ricardo,

Imagino que quieres ejecutar la [aplicación web de LibreDTE](https://github.com/LibreDTE/libredte-webapp), dejé un archivo [INSTALL.md](https://github.com/LibreDTE/libredte-webapp/blob/master/INSTALL.md) en el repositorio explicando como habría que hacerlo. Eso si, el [módulo Dte](https://github.com/LibreDTE/libredte-sowerphp) necesario para que la aplicación web funcione aun no está liberado, por lo cual tendrás básicamente sólo la página web, pero no la aplicación para generar DTEs.

Cerraré la issue en este repositorio (este es el de la biblioteca, no de la webapp), si necesitas ayuda con esto nuevamente te pido abras una nueva pero [en el repositorio de la aplicación web](https://github.com/LibreDTE/libredte-webapp/issues).

Saludos!

**Comment by estebandelaf** [comment]
Se liberó la versión de desarrllo del Módulo Dte https://github.com/LibreDTE/libredte-sowerphp

Saludos!
