### ISSUE TITLE
Problema al generar 'xmlns' => 'http://www.w3.org/2000/09/xmldsig#' del Signature

### ISSUE THREAD

**Issue by pzapata87** [LibreDTE/libredte-lib#47]
Hola a todos,

Estoy usando esta librería para firmar documentos, para a la hora de generar el Signature ocurre un problema, no se genera el atributo 'xmlns' => 'http://www.w3.org/2000/09/xmldsig#' del Signature y según veo hay algo que se lo quita cuando se utiliza el método "appendChild", por favor me podrian decir por que pasa eso?.
Saludos,

**Comment by estebandelaf** [comment]
De esa forma lo acepta el SII.

Si tienes un problema, por favor adjunta el enlace al repositorio con el código fuente de tu aplicación indicando cuál es la parte que genera el código y el error.

**Comment by pzapata87** [comment]
No estoy validando directamente con el SII, si no que estoy usando una librería que valida el signature, y para ello se necesita de 'xmlns' => 'http://www.w3.org/2000/09/xmldsig#' en el tag "Signature", por ello te agradecería si sabes por que lo quita el "appendChild".

**Comment by estebandelaf** [comment]
La biblioteca de LibreDTE cumple con el que el SII pide, que no es necesariamente lo que el estándar pide. Hay detalles de esto en https://www.cryptosys.net/pki/xmldsig-ChileSII.html

Se quita, porque de estar el SII no valida la firma (al menos en la época que se hizo, año 2014-2015, era así).
