### ISSUE TITLE
Consulta, boleta electronica

### ISSUE THREAD

**Issue by eliseozavala** [LibreDTE/libredte-lib#48]
Hola soy eliseo zavala desarrollador chileno igual, queria preguntar si por casualidad ya haz visto alguna solucion a la boleta electronica?.... y aparte de eso, me podrias guiar en donde buscar informacion sobre estos temas factura y boleta electronica? 
de antemanos Gracias!

**Comment by estebandelaf** [comment]
Ejemplos 029 al 032: https://github.com/LibreDTE/libredte-lib/tree/master/examples 

Resto de información en SII en http://www.sii.cl/factura_electronica/factura_mercado/instructivo.htm
