### ISSUE TITLE
Ayuda a Crear firma de XML

### ISSUE THREAD

**Issue by kelgar765** [LibreDTE/libredte-lib#49]
buenas, amigo interesante tu trabajo, estoy desarrollando un proceso para firmar documentos  de facturas electrónicas de costa rica, podrías orientarme a como funciona el proceso de firmar documentos., he tratado de hacerlo con el código que tienes pero me falta información de como funciona.

**Comment by estebandelaf** [comment]
https://www.cryptosys.net/pki/xmldsig-ChileSII.html

En ese enlace está explicado el proceso de firma electrónica para Chile. Te podría servir de guía.

Si quieres usar nuestro código de  base, ningún problema, sólo recuerda publicar tu código fuente ya que lo exige nuestra licencia :-)

**Comment by kelgar765** [comment]
Amigo as tenido relación con la facturación electrónica de costa rica. ?

estoy estancado en un error que me arroja la api. no consigo información al
respecto.

hacienda de costa rica no da respuesta.

el error que me retorna la api es:

- El XML de respuesta que les dio la plataforma.

 <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /api/v1/. Reason:
<pre>    Not Found</pre></p><hr><i><small>Powered by
Jetty://</small></i><hr/>

</body>
</html>

**Comment by estebandelaf** [comment]
No, no he trabajado con la de Costa Rica, sólo Chile.

Ojo que lo que mandaste no es un XML, es sólo HTML (y de un error 404).

La issue se cierra, ya que no se resolverá al ser de otro país el caso.

**Comment by kelgar765** [comment]
si estoy consciente de que es código html en ves de xml, solo quería saber
si alguna vez viste algún tipo de error así, o si conocías esa plataforma
también,
gracias por tu respuesta si puedes cerrar la issue.


si logro resolver o me dan la solución en hacienda de costa rica  te
comento para conocimiento.

saludos.
