### ISSUE TITLE
Importación del Certificado

### ISSUE THREAD

**Issue by factronico** [LibreDTE/libredte-lib#5]
No hubo caso con la importación del certificado ni en pfx ni p12 se pudo.
Arroja un error en mysql.
Lo realizé en el módulo dte para generar un xml en producción pero no funcionó.

**Comment by estebandelaf** [comment]
Si te refieres al módulo Dte para la aplicación web (que usa postgresql) te agradecería abrir una issue en el repositorio correspondiente https://github.com/LibreDTE/libredte-sowerphp o bien escribir en el grupo de google https://groups.google.com/forum/#!forum/libredte En cualquiera de los dos casos te pido adjuntar el error para poder resolver el problema. Saludos!

**Comment by estebandelaf** [comment]
Se agregó soporte para certificados E-Sign https://github.com/LibreDTE/libredte-lib/commit/8aaad263f83c138b6706a3ffc552dd66126a1013

**Comment by estebandelaf** [comment]
Se agreggó soporte para E-CERTCHILE[1] de acuerdo a listado de firmas oficiales[2] sólo falta agregar el soporte para certificados de CERTINET.

[1] https://github.com/LibreDTE/libredte-lib/commit/84293b898927cb8e3a978b8fb2fcd536cdd48359
[2] https://palena.sii.cl/dte/mn_Prov_CD.html

**Comment by estebandelaf** [comment]
Son 5 las empresas autorizadas a emitir firmas[1], no 4 (la página del SII[2] está desactualizada ¬¬). 

Se agregó soporte para PKI Chile: Paperless[3]. Sigue faltando el soporte para CERTINET.

[1] https://github.com/LibreDTE/libredte-lib/commit/0faf45e8107735e3460d5a5f299f92af60b4d81b
[2] https://palena.sii.cl/dte/mn_Prov_CD.html
[3] http://www.entidadacreditadora.gob.cl/?page_id=136

**Comment by estebandelaf** [comment]
Se me ocurrió revisar si Acepta e E-Sign guardaban el RUN en la extensión, al igual que PAPERLESS y E-CERTCHILE. Y efectivamente ahí lo guardan, mi confusión original era porque Acepta e E-sign además lo guardaban en otro lado. Asumiré que si los 4 proveedores lo guardan en la extensión, es la forma estándar de guardarlo ya que no me cuadra que cada proveedor lo guarde en un campo diferente. Por lo anterior, supongo el 5to proveedor estaría soportado y cierro la issue.

**Comment by estebandelaf** [comment]
Efectivamente, todos lo guardan en el mismo campo, está en la Ley https://archivos.libredte.cl/sii/ley/ley_19799_documento_electronico.pdf página 18 y 19.
