### ISSUE TITLE
Duda licencia libreDTE

### ISSUE THREAD

**Issue by falvarezh90** [LibreDTE/libredte-lib#55]
Hola! Tengo una duda con la licencia de libre DTE, quería consultar si puedo crear una API con esta bilbioteca, liberar este código bajo la licencia correspondiente, pero además crear un software aparte que consuma los servicios de la API, pero no liberar el código de este último.  Saludos.

**Comment by estebandelaf** [comment]
Si la API son servicios web y es completamente liberada bajo una licencia compatible con AGPL, si, puedes. Ya que son dos software independientes, uno es el que compatible con LibreDTE (los servicios web) y otro es el software que consume esos servicios web (cualquier licencia). Lo que no podrías hacer por ejemplo es crear una API que sólo sea wrappers (no servicios web) y luego incluirlos directamente en tu código.

Recuerda que para poder usar LibreDTE bajo AGPL se debe cumplir con los términos y condiciones del proyecto, disponibles en https://wiki.libredte.cl/doku.php/terminos En caso de no cumplir con dichos términos no está autorizado el uso de LibreDTE bajo AGPL.
