### ISSUE TITLE
ayuda Xml EnvioBoleta

### ISSUE THREAD

**Issue by jgrandon** [LibreDTE/libredte-lib#57]
Hola! poseo un software de facturación y estoy trabajando en la elaboracion del xml EnvioBOLETAS para certificacion. Estamos teniendo problemas hace meses porque el SII se demora de 7 a15 dias en responder cada envio y una vez que lo rechazan le hacemos modificaciones y lo volvemos a enviar. Se que no tiene que ver con tu proyecto y te pido disculpas de antemano, pero me ayudaria mucho si pudieras compartirme un xml ya generado de EnvioBOLETAS. En general nos estan rechazando por errores de esquema del xml y con uno ya generado correctamente podria corregir el mio.
Muchas gracias!

**Comment by estebandelaf** [comment]
Hola, puedes generar un XML válido con tus datos con el ejemplo:

https://github.com/LibreDTE/libredte-lib/blob/master/examples/032-boleta_simulacion.php
