### ISSUE TITLE
Descuento con decimales

### ISSUE THREAD

**Issue by Adoniasv** [LibreDTE/libredte-lib#58]
Hola

en el namespace sasco\LibreDTE\Sii\DTE en donde dice:

```
// aplicar descuento 
if ($d['DescuentoPct']) {
   $d['DescuentoMonto'] = round($d['MontoItem'] * (int)$d['DescuentoPct']/100);
}
```

```
// aplicar descuento
if ($d['DescuentoPct']) {
   $d['DescuentoMonto'] = round($d['MontoItem'] * (float)$d['DescuentoPct']/100);
}
```

Debería ser un float, ya que muchas veces los porcentajes son en decimales.

**Comment by estebandelaf** [comment]
Listo: https://github.com/LibreDTE/libredte-lib/commit/9b7b51f5a24878f91f75992ad0cb50882d2f45b6
