### ISSUE TITLE
Carpeta xml en ejemplos

### ISSUE THREAD

**Issue by XzAeRo** [LibreDTE/libredte-lib#59]
Es posible que se suba la carpeta `xml` a la cual se hace referencia en varios de los ejemplos en la carpeta `examples`?

Ej:
 - `xml/certificado/set_pruebas/set_pruebas_basico.xml`
- `xml/folios.xml`
- `xml/intercambio/ENVIO_DTE_420328.xml`

Lo consulto para hacer mas sencillo hacer funcionar los ejemplos, ya que he tenido que estar creando cada uno de esos archivos a mano, y quizás sea mas sencillo para otras personas "llegar y correr" los ejemplos.

Saludos y gracias por esta maravillosa librería!

**Comment by estebandelaf** [comment]
Todos esos archivos los provee el SII o son archivos que se van generando con los mismos ejemplos.

Los 3 casos que menciona, corresponden a archivos que el SII entrega.

Por lo anterior, estos archivos no se incluyen y deben ser incorporados por cada empresa según los propios archivos XML asignados.

**Comment by XzAeRo** [comment]
Gracias por la clarificación. Podría sugerir añadir eso al README?

**Comment by estebandelaf** [comment]
Agregado.
