### ISSUE TITLE
Origen de certificados públicos SII

### ISSUE THREAD

**Issue by jtrh** [LibreDTE/libredte-lib#61]
Hola.

Quería consultar cuál es la fuente de los certificados públicos del SII que se incluyen en este repositorio:
- [100 / Maullin / Certificación](https://github.com/LibreDTE/libredte-lib/blob/06f03bdf16b95a3f7246a72ac5ca465f137f435b/certs/100.cer)
- [300 / Palena / Producción](https://github.com/LibreDTE/libredte-lib/blob/06f03bdf16b95a3f7246a72ac5ca465f137f435b/certs/300.cer)

Me interesa saber si hay alguna forma de obtener esos archivos directamente desde el SII.

Gracias.

**Comment by estebandelaf** [comment]
Si mal no recuerdo, los saqué de acá:

https://www.cryptosys.net/pki/xmldsig-ChileSII.html

No recuerdo haberlos obtenido directo del SII. Si los encuentras en un enlace oficial del SII comenta en esta issue y agregó la info en un readme en el directorio de los certificados.
