### ISSUE TITLE
Problema en conversión XML a arreglo usando nodos con mismo nombre

### ISSUE THREAD

**Issue by estebandelaf** [LibreDTE/libredte-lib#62]
La clase \sasco\LibreDTE\XML permite cargar el contenido de un archivo XML y convertir este XML a un arreglo en PHP.

Cuando hay un nodo que se repite más de una vez se crea un arreglo con dichos nodos. Ejemplo, si tenemos el XML:

```xml
<Documento>
    <Detalle> blabla 1 </Detalle>
    <Detalle> blabla 2 </Detalle>
</Documento>
```

Se crea el arreglo PHP:

```php
[
    'Documento' => [
        'Detalle' => [
            'bla bla 1',
            'bla bla 2',
        ],
    ],
]
```

O sea, se crea un arreglo con el nombre del nodo que se repite en el mismo nivel y se coloca cada nodo que repite su nombre como un elemento del arreglo.

Lo anterior funciona bien, de hecho es la base de LibreDTE y lleva años funcionando bien. Sin embargo, hay un caso que se detectó donde la conversión de XML a arreglo PHP falla:

Si el XML contiene un nodo que se repite en el mismo nivel (ej: nodo Detalle) y este a su vez tiene otro nodo que se repite en el mismo nivel (ej: nodo Subcantidad) entonces en este caso el resultado del arreglo PHP no es el esperado y falla.

Ejemplo que da problemas:

```xml
<Documento>
    <Detalle>
        <Subcantidad> código 1 </Subcantidad>
        <Subcantidad> código 2 </Subcantidad>
    </Detalle>
    <Detalle> 
        <Subcantidad> código 3 </Subcantidad>
        <Subcantidad> código 4 </Subcantidad>
     </Detalle>
</Documento>
```

Lo esperado es:

```php
[
    'Documento' => [
        'Detalle' => [
            [
                'Subcantidad' => [
                    'código 1',
                    'código 2',
                ],
            ],
            [
                'Subcantidad' => [
                    'código 3',
                    'código 4',
                ],
            ],
        ],
    ],
]
```

Sin embargo el resultado es otro e incorrecto.

No es algo grave para la versión oficial en www.libredte.cl ya que oficialmente no se soporta el tag Subcantidad. Los usuarios que lo usan lo usan sólo una vez, sin repetir el tag Subcantidad dentro de un mismo detalle y en este caso (si no hay repetición) no se producen problemas.

El código a corregir está en el método XML::toArray() en https://github.com/LibreDTE/libredte-lib/blob/master/lib/XML.php#L265

Se deja abierta la issue para futura referencia y corrección cuando se decida hacer.

**Comment by ffflabs** [comment]
#### 1. Si te fijas, salvo en el caso que no se pase un DOMElement y la instancia no tenga un documento cargado
https://github.com/LibreDTE/libredte-lib/blob/b75b92347223f422176b2f200c1599aa5d9df49f/lib/XML.php#L228-L230

En todos los otros casos  el flujo de   `XML::toArray()` muy resumido es

```php
public function toArray(\DOMElement $dom = null, array &$array = null) {
   $array[$dom->tagName] =  $ContenidoDelDOM; // lo que sea que contenga
   return $array;
}
```
De manera que la salida siempre tiene la forma

```php
 [$dom->tagName =>  $ContenidoDelDOM]
}
```
El segundo parámetro es mutado añadiéndosele una llave `$dom->tagName`


#### 2. Cuando tienes elementos repetidos y creas a mano el índice numérico de los siblings para pasar por referencia al siguiente llamado de `toArray`

https://github.com/LibreDTE/libredte-lib/blob/b75b92347223f422176b2f200c1599aa5d9df49f/lib/XML.php#L271-L273

Estás declarando (por ejemplo)
```php
$array['Documento']['Detalle'][0]=[];
```
y luego cuando lo pasas al llamado recursivo
```php
$this->toArray($child, $array['Documento']['Detalle'][0], true);
```
El segundo parámetro será mutado añadiéndosele una llave 'Detalle'. Luego quedará:

```php
$array['Documento']['Detalle']=[
    'Detalle'  => $ContenidoDetalle
];
```

Y por eso se duplica telescópicamente.



#### 3. Cuando se indica a una recursión que es un `arregloNodos`, el único efecto que tiene es en

https://github.com/LibreDTE/libredte-lib/blob/b75b92347223f422176b2f200c1599aa5d9df49f/lib/XML.php#L256-L263

Me parece que esa condición está ahí para añadir un nodo directo al array y no a la llave proveniente de tagName, Pero justamente en el caso de tags anidados nunca ocurrirá que los nodos gemelos sean uno solo.


#### Mi sugerencia

Aprovechando que el método no solamente muta el array sino que retorna su contenido, me parece que se podría minimizar los side effects si el valor de $array se va completando a partir del retorno de las llamadas recursivas y no a partir de mutaciones.

Por ejemplo, estando parados en una línea de detalle, se podría hacer:


```php
$childArray = []; 
$output=$this->toArray($child, $childArray, true);
```

Y ese $output sería 

```php
[ 'Detalle'  => $ContenidoDetalle]
```

De manera que luego de inicializa el array 'Detalle' en el padre puedes pushear al arreglo sin tener que contar los nodos, pero más importante, puedes evitar la llave duplicada

```php
$array[$dom->tagName][$child->tagName]=$array[$dom->tagName][$child->tagName]??[];
$array[$dom->tagName][$child->tagName][] = $output[$child->tagName]??$output;
```
(la coalescencia de output es por si entra a nodos gemelos === 1 y arregloNodos = true, que no devolvería el tagName repetido.

**La cosa quedaría así:**

```php
 if ($nodos_gemelos==1) {
            // ...
   }
   // crear arreglo con nodos hijos que tienen el mismo nombre de tag
    else {
    $childArray = [];
    $output = $this->toArray($child, $childArray, true);
    $array[$dom->tagName][$child->tagName] = $array[$dom->tagName][$child->tagName]??[];
    $array[$dom->tagName][$child->tagName][] = $output[$child->tagName]??$output;
 }
```

**Comment by estebandelaf** [comment]
Gracias por el análisis.

Es algo que en algún momento futuro se debería corregir. El 2021 pretendo hacer algunos cambios al núcleo en cuanto a revisión de errores, crear pruebas y estilo de código. En ese momento podría ser buena idea retomar esta issue.

Sin embargo, al no ser algo que afecte a www.libredte.cl no tiene prioridad para ser corregido, al menos no de mi parte por ahora.

Lo que indicas queda como antecedente para una eventual corrección. Probablemente se pruebe directamente tu solución con algunos tests que se crearán y si los pasa se aplica el cambio. ¡gracias!
