### ISSUE TITLE
Cambio en Formato Boletas Electrónicas 20 jul 2020

### ISSUE THREAD

**Issue by jesustejerina** [LibreDTE/libredte-lib#65]
Hubo cambios en las boletas electrónicas, se han considerado ya dichos cambios??

REF: http://www.sii.cl/normativa_legislacion/resoluciones/2020/reso74.pdf

**Comment by estebandelaf** [comment]
Esos cambios serán publicados en el futuro, eventualmente, pero no hay fecha definida.

**Comment by jesustejerina** [comment]
OK, adjunto detalle de cambios. http://www.sii.cl/factura_electronica/factura_mercado/boletas_elec_020.pdf
