### ISSUE TITLE
Soporte para PHP 7.4

### ISSUE THREAD

**Issue by dleo** [LibreDTE/libredte-lib#67]
Hola Esteban,

¿Esta pensando el soporte para PHP 7.4?

Si la repuesta es sí, podríamos empezar con una lista de librerías que estén adecuadas y comprobar si cumplen con los requisitos.

Por por un ejemplo, al momento la versión de la librería tecnickcom/tcpdf en la versión 6.2.26 no lo soporta y así posiblemente habrán otras.

**Comment by estebandelaf** [comment]
Por el momento no.

La distribución oficialmente soportada es Debian GNU/Linux, y actualmente está en la versión 10 con PHP 7.3

Si en el futuro sale una actualización a PHP 7.4 o bien sale antes Debian GNU/Linux 11 con PHP 7.4 lo tendré en cuenta, pero no antes de eso.

De todas maneras, PHP 7.3 tiene soporte hasta diciembre de 2021 y es probable, aunque no está confirmada la fecha, que Debian GNU/Linux 11 salga el 2021.

También es muy probable, en eso si he estado más atento, que el paso por 7.4 sea breve y se deba migrar rápido a versión 8. Pero claro, estoy pensando a 2 años más por lo menos.
