### ISSUE TITLE
response STATUS -1 en EnvioDTE

### ISSUE THREAD

**Issue by jesustejerina** [LibreDTE/libredte-lib#69]
Buen día, desde ayer los envíos me estan devolviendo STATUS -1: ambiente certificación:
object(SimpleXMLElement)#1797 (5) { ["RUTSENDER"]=> string(10) "08736349-0" ["RUTCOMPANY"]=> string(3) "0-0" ["FILE"]=> object(SimpleXMLElement)#1792 (0) { } ["TIMESTAMP"]=> string(3) "0 0" ["STATUS"]=> string(2) "-1" }.

el XML generado lo subí directamente por SII y lo aceptó normalmente con lo que verifico que el XML esta bien formado.

Revisé el archivo Sii.php y no ha cambiado nada con la actualización 20.07

Tomé como referencia el ejemplo 004-envioDte.php

Algo ha cambiado en algún otro lugar??

ACTUALIZO: Probé la versión antigua de libreDTE (unas pruebas antiguas) la q se instalaba con dev-master y funciona perfecto... al parecer es problema al hacer composer update que te lleva a la versión 20.07

Saludos y gracias por su gran aporte.

**Comment by estebandelaf** [comment]
No hay problemas en certificación en nuestras plataformas, ni la oficial, ni la de desarrollo, ni la API.

No fue posible reproducir lo que comenta, ya que todo está ok por nuestro lado.

Es probable que tenga algún otro problema.

**Comment by jesustejerina** [comment]
**ACTUALIZACIÓN:**
Al parecer luego de hacer actualizaciones automáticas en mi entorno de desarrollo LINUX es que dejó de funcionar por alguna razón. Llevé el proyecto a entorno windows y funcionó sin ningún problema los envíos con la actualización 20.07 de LibreDTE.

**Comment by jesustejerina** [comment]
**ACTUALIZACIÓN FINAL:**
Probé con una copia de seguridad y funcionaba, probé en windows y funcionaba....
Resultó que en linux había actualizado a php7.4 y el curl de envíos no funcionaba... Desinstalé completamente php7.4 con todas sus dependencias, luego instalé php7.3 con todas sus dependencias y FUNCIONOOOOO....

Saludos...
