### ISSUE TITLE
Duplica Calculo Monto Total Boletas

### ISSUE THREAD

**Issue by jesustejerina** [LibreDTE/libredte-lib#71]
Que tal colegas, un probable aporte.
En Dte.php método normalizar_detalle linea 1482 ( $datos['Encabezado']['Totales']['MntTotal'] += $d['MontoItem'];) se hace la sumatoria del items para las boletas asumiendo que no se ha calculado el MntTotal o que inicialmente es cero.
Pero cuando haces por ejemplo el RCOF debes agregar los DTE de boletas ya existentes  que vienen con MntTotal ya calculado mayor a cero, entonces MntTotal+=MntItem allí lo duplica.
Mi primera solución es:
Al inicio de normalizar_detalle colocar:
if($this->esBoleta()){
            $datos['Encabezado']['Totales']['MntTotal']=0; //Porque abajo lo recalcula...
 }

Sólo me falta comprobar la generación nueva de un DTE para boletas y calcule adecuadamente MntTotal.

Saludos

**Comment by estebandelaf** [comment]
¿Cuál es el caso de error que esto produce? No tenemos ningún error en la versión oficial por lo descrito, los RCOF se general ok.
Aunque es probable también un tema de uso de la biblioteca si es con software externo.

¿La biblioteca la usa con la versión comunidad de LibreDTE o en un software propio?
