### ISSUE TITLE
Registro de compra venta - TOKEN invalido

### ISSUE THREAD

**Issue by GravityCube** [LibreDTE/libredte-lib#72]
Estuve probando y al parecer el wsdl de certificación, en el RCV, requiere un token de producción para poder acceder a los datos requeridos.

Dejo un pequeño parche ya que no sé donde podría reportar esto al SII:

```php 
    public function __construct(\sasco\LibreDTE\FirmaElectronica $Firma)
    {
        $ambienteAntiguo = Sii::getAmbiente();
        Sii::setAmbiente(Sii::PRODUCCION);
        $this->token = \sasco\LibreDTE\Sii\Autenticacion::getToken($Firma);
        Sii::setAmbiente($ambienteAntiguo);
        if (!$this->token) {
            throw new \Exception('No fue posible obtener el token para la sesión del RCV');
        }
    }
```
https://github.com/LibreDTE/libredte-lib/blob/89e56d2fba007d7eb25bce6ff50a05c212ba1746/lib/Sii/RegistroCompraVenta.php#L87-L93

**Comment by estebandelaf** [comment]
Pude reproducir lo indicado, y efectivamente con un token de producción no hay problemas en certificación.

Antes no era así, pero si SII hizo algún cambio, esperemos que sea definitivo. De todas formas si en el futuro es necesario revertir se hace.

Por ahora, quedó aplicado el cambio sugerido en https://github.com/LibreDTE/libredte-lib/commit/da8ed0b77cccb2fba0b36b0db73720bdf916dcdd
