### ISSUE TITLE
Calculo erroneo en el total de una boleta cuando se tiene un producto con impuesto adicional

### ISSUE THREAD

**Issue by marchantm** [LibreDTE/libredte-lib#76]
Al enviar productos con impuesto adicional vuelve a sumar el valor neto al valor total y en la impresión no muestra el impuesto adicional.

**Comment by npho111** [comment]
Hola, para generar una Factura electronicas CL33 con descuento global e impuestos adicionales, deben ser emitidas desactivando la normalización por el momento como en este caso?

Ya que al enviar impuestos adicionales con un descuento global estos impuestos adicionales son sumados al monto total sin aplicarles el descuento global.

saludos y gracias de antemano.
