### ISSUE TITLE
enviar boleta al sii queda pegado en CRT

### ISSUE THREAD

**Issue by bikotoru** [LibreDTE/libredte-lib#77]
Hola a alguien más le ha ocurrido que al enviar las boletas a la API del SII, esta queda pegado en CRT, incluso al volver a mandarlo sigue pegado ahi

**Comment by estebandelaf** [comment]
https://github.com/LibreDTE/libredte-lib no posee envío de boletas al SII.

**Comment by newmesiss** [comment]
hola aún no tiene la opción de envío de boletas electrónicas?

**Comment by estebandelaf** [comment]
@newmesiss no, no es una opción disponible en la biblioteca.
