### ISSUE TITLE
RUT Receptor (Caratula) Invalido - [XXXX6500-1]

### ISSUE THREAD

**Issue by wilfredinni** [LibreDTE/libredte-lib#78]
Hola a todos,

Cuando coloco el RUT del SII en Caratula -> RutReceptor no da problemas (60803000-K) pero cuando coloco el RUT del receptor da error de Carátula.

Tenemos algunos clientes que su software no acepta con el RUT del SII (como Paperless, Sovo)

Muchas gracias por su contribución al OS

**Comment by estebandelaf** [comment]
Si lo envías al cliente debe ir con RUT del cliente, si lo envías al SII, debe ir con RUT del SII.

**Comment by cesarcsr9** [comment]
> Hola a todos,
> 
> Cuando coloco el RUT del SII en Caratula -> RutReceptor no da problemas (60803000-K) pero cuando coloco el RUT del receptor da error de Carátula.
> 
> Tenemos algunos clientes que su software no acepta con el RUT del SII (como Paperless, Sovo)
> 
> Muchas gracias por su contribución al OS

Estimado, me sucede lo mismo, que era al final?

**Comment by newmesiss** [comment]
> > Hola a todos,
> > Cuando coloco el RUT del SII en Caratula -> RutReceptor no da problemas (60803000-K) pero cuando coloco el RUT del receptor da error de Carátula.
> > Tenemos algunos clientes que su software no acepta con el RUT del SII (como Paperless, Sovo)
> > Muchas gracias por su contribución al OS
> 
> Estimado, me sucede lo mismo, que era al final?

supongo que a esta altura lo solucionaste ?

**Comment by cesarcsr9** [comment]
Hola Luis el rut receptor de la carátula debe ser el rut del sii es el que
recibe: <RutReceptor>60803000-K</RutReceptor>
