### ISSUE TITLE
Nota de crédito para DTE

### ISSUE THREAD

**Issue by BastiiNicolas** [LibreDTE/libredte-lib#79]
Es posible generar esta nota de crédito a un DTE ? Generalmente se hace una nota de crédito en el SII referenciando el folio y poniendo una glosa, netamente para temas contables. 
Si tuviesen ese endpoint y json como para poder automatizar este proceso sería genial ya que no lo encuentro :C

**Comment by estebandelaf** [comment]
La biblioteca de LibreDTE si permite generar notas de crédito.

Si eres cliente de www.libredte.cl puedes encontrar la documentación en http://libredte.cl/doc
